
package com.yapengren.bos.service.take_delivery.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServiceImpl", targetNamespace = "http://impl.take_delivery.service.bos.yapengren.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServiceImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://impl.take_delivery.service.bos.yapengren.com/", className = "com.yapengren.bos.service.take_delivery.impl.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://impl.take_delivery.service.bos.yapengren.com/", className = "com.yapengren.bos.service.take_delivery.impl.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
